_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 2
                - 5
                - 14
                - 23
                - 55
                - 62
            "4": 3.11.10
            "5": 0.19.11
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
accum_iter:
    value: 1
batch_size:
    value: 256
blr:
    value: 0.01
checkpoint:
    value: /niddk-data-central/leo_workspace/MoCA_result/ckpt/iWatch-Hipps_5_mask_0.75_bs_256_blr_None_epoch_100/2025-04-23_20-41/checkpoint-20.pth
clip_grad:
    value: null
data_path:
    value: /niddk-data-central/iWatch/pre_processed_seg/H
device:
    value: cuda
dist_backend:
    value: nccl
dist_eval:
    value: false
dist_on_itp:
    value: false
dist_url:
    value: env://
distributed:
    value: true
ds_name:
    value: iwatch
epochs:
    value: 20
eval:
    value: null
gpu:
    value: 0
in_chans:
    value: 3
input_size:
    value:
        - 3
        - 100
local_rank:
    value: -1
log_dir:
    value: /niddk-data-central/leo_workspace/MoCA_result/LP/log/Hip_20epochLP_blr_0.01_bs_256_input_size_[3, 100]/2025-04-27_02-37
lr:
    value: null
min_lr:
    value: 1e-06
model:
    value: vit_base_patch16
nb_classes:
    value: 2
num_workers:
    value: 2
output_dir:
    value: /niddk-data-central/leo_workspace/MoCA_result/LP/ckpt/Hip_20epochLP_blr_0.01_bs_256_input_size_[3, 100]/2025-04-27_02-37
patch_size:
    value: 5
pin_mem:
    value: true
rank:
    value: 0
remark:
    value: Hip_20epochLP_blr_0.01_bs_256_input_size_[3, 100]
resume:
    value: ""
seed:
    value: 0
start_epoch:
    value: 0
warmup_epochs:
    value: 2
weight_decay:
    value: 0
world_size:
    value: 4
