torchrun --nproc_per_node=4 -m main_finetune_long \
--ds_name iwatch \
--data_path "/niddk-data-central/SOL/PASOS/train/SOL_10hz" \
--remark shallow-moca-scratch  \
--model shallow-moca \
--blr 1e-3 \
--weight_decay 1e-3 \
--epochs 10 \
--warmup_epochs 2 \
--batch_size 16 \
--num_attn_layer 2 \
--use_pos_embed \
--pos_weight=1.0 \
--subset_ratio 1.0 
