torchrun --nproc_per_node=8 main_pretrain.py \
--data_path /niddk-data-central/SOL/PASOS/train/SOL_10hz \
--batch_size 12 \
--world_size 8 \
--epochs 100 \
--warmup_epochs 10 \
--std_sampling \
--remark SOL \
--save_freq 2 \
--mask_ratio 0.75 \
--resume "/niddk-data-central/leo_workspace/MoCA_result/ckpt/SOLps_5_mask_0.75_bs_12_blr_None_epoch_100/2025-07-25_04-21"
