model:
  name: AttentionInteractionModel
  hidden_dim: 768 #256
  num_heads: 8
  num_layers: 4
  ffn_multiplier: 4
  transfer_learning_model_path: "/DeepPostures_MAE/MSSE_2021_pt/pre-trained-models-pt/CHAP_ALL_ADULTS.pth"
  drop_path_rate: 0.4 # default 0.1
  learnable_pos_embed: True
  
# optimizer:
#   name: adamw
#   lr: 0.001
#   weight_decay: 0.05

# data:
#   train_path: /mnt/data/train
#   val_path: /mnt/data/val
